# -*- coding: utf-8 -*-
"""Soal UTS 2 Singly Linked List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-wefESk94QSCMsFl3FPgrMswKugYFt3
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None


class LinkedList:
    def __init__(self):
        self.head = None

    # Insert di akhir
    def insert_akhir(self, data):
        node_baru = Node(data)

        if self.head is None:
            self.head = node_baru
        else:
            temp = self.head
            while temp.next:
                temp = temp.next
            temp.next = node_baru

    # Insert di awal
    def insert_awal(self, data):
        node_baru = Node(data)
        node_baru.next = self.head
        self.head = node_baru

    # Tampilkan data
    def tampilkan(self):
        temp = self.head

        while temp:
            print(temp.data, end=" -> ")
            temp = temp.next

        print("None")

    # Cari data
    def cari(self, data):
        temp = self.head

        while temp:
            if temp.data == data:
                return True
            temp = temp.next

        return False

    # Hapus data
    def hapus(self, data):
        temp = self.head

        if temp and temp.data == data:
            self.head = temp.next
            return

        prev = None

        while temp and temp.data != data:
            prev = temp
            temp = temp.next

        if temp is None:
            print("Data tidak ditemukan")
            return

        prev.next = temp.next


# Program utama
ll = LinkedList()

# Insert data
ll.insert_akhir(10)
ll.insert_akhir(20)
ll.insert_akhir(30)
ll.insert_akhir(40)

print("Hasil Linked List:")
ll.tampilkan()

# Cari data
cari = 30
print("\nCari data:", cari)

if ll.cari(cari):
    print("Data ditemukan")
else:
    print("Data tidak ditemukan")

# Hapus data
hapus = 20
print("\nHapus data:", hapus)

ll.hapus(hapus)

print("Data setelah dihapus:")
ll.tampilkan()