# -*- coding: utf-8 -*-
"""Soal UTS 3 Manajemen Singly Playlist Musik.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-wefESk94QSCMsFl3FPgrMswKugYFt3
"""

class Node:
    def __init__(self, judul, penyanyi):
        self.judul = judul
        self.penyanyi = penyanyi
        self.next = None
        self.prev = None


class CircularDoublyLinkedList:
    def __init__(self):
        self.head = None
        self.current = None

    # Tambah lagu
    def tambah_lagu(self, judul, penyanyi):
        lagu_baru = Node(judul, penyanyi)

        if self.head is None:
            self.head = lagu_baru
            lagu_baru.next = lagu_baru
            lagu_baru.prev = lagu_baru
            self.current = lagu_baru
        else:
            tail = self.head.prev

            tail.next = lagu_baru
            lagu_baru.prev = tail

            lagu_baru.next = self.head
            self.head.prev = lagu_baru

    # Tampilkan playlist
    def tampilkan_playlist(self):
        if self.head is None:
            print("Playlist kosong")
            return

        temp = self.head

        while True:
            print(f"{temp.judul} - {temp.penyanyi}")
            temp = temp.next

            if temp == self.head:
                break

    # Next lagu
    def next_lagu(self):
        if self.current:
            self.current = self.current.next
            print("Now Playing:")
            print(f"{self.current.judul} - {self.current.penyanyi}")

    # Prev lagu
    def prev_lagu(self):
        if self.current:
            self.current = self.current.prev
            print("Now Playing:")
            print(f"{self.current.judul} - {self.current.penyanyi}")

    # Cari lagu
    def cari_lagu(self, judul):
        if self.head is None:
            print("Playlist kosong")
            return

        temp = self.head

        while True:
            if temp.judul.lower() == judul.lower():
                print("Lagu ditemukan:")
                print(f"{temp.judul} - {temp.penyanyi}")
                return

            temp = temp.next

            if temp == self.head:
                break

        print("Lagu tidak ditemukan")

    # Hapus lagu
    def hapus_lagu(self, judul):
        if self.head is None:
            print("Playlist kosong")
            return

        temp = self.head

        while True:
            if temp.judul.lower() == judul.lower():

                # Jika hanya satu node
                if temp.next == temp:
                    self.head = None
                    self.current = None

                else:
                    temp.prev.next = temp.next
                    temp.next.prev = temp.prev

                    if temp == self.head:
                        self.head = temp.next

                    if temp == self.current:
                        self.current = temp.next

                print("Lagu berhasil dihapus")
                return

            temp = temp.next

            if temp == self.head:
                break

        print("Lagu tidak ditemukan")


# Program utama
playlist = CircularDoublyLinkedList()

while True:
    print("\n===== MENU PLAYLIST =====")
    print("1. Tambah Lagu")
    print("2. Hapus Lagu")
    print("3. Tampilkan Playlist")
    print("4. Next Lagu")
    print("5. Prev Lagu")
    print("6. Cari Lagu")
    print("7. Keluar")

    pilihan = input("Pilih menu: ")

    if pilihan == "1":
        judul = input("Masukkan judul lagu: ")
        penyanyi = input("Masukkan nama penyanyi: ")

        playlist.tambah_lagu(judul, penyanyi)

    elif pilihan == "2":
        judul = input("Masukkan judul lagu yang ingin dihapus: ")
        playlist.hapus_lagu(judul)

    elif pilihan == "3":
        print("\nPlaylist:")
        playlist.tampilkan_playlist()

    elif pilihan == "4":
        playlist.next_lagu()

    elif pilihan == "5":
        playlist.prev_lagu()

    elif pilihan == "6":
        judul = input("Masukkan judul lagu yang dicari: ")
        playlist.cari_lagu(judul)

    elif pilihan == "7":
        print("Program selesai")
        break

    else:
        print("Pilihan tidak valid")