# -*- coding: utf-8 -*-
"""Soal UTS 1 Mengelola Data Mahasiswa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-wefESk94QSCMsFl3FPgrMswKugYFt3
"""

# Fungsi menampilkan data
def tampilkan_nilai(data):
    print("Daftar Nilai:", data)

# Fungsi tambah nilai
def tambah_nilai(data, nilai):
    data.append(nilai)
    print("Data setelah ditambah:", data)

# Fungsi hapus nilai
def hapus_nilai(data, nilai):
    if nilai in data:
        data.remove(nilai)
        print("Data setelah dihapus:", data)
    else:
        print("Nilai tidak ditemukan")

# Fungsi hitung rata-rata
def rata_rata(data):
    total = 0

    for nilai in data:
        total += nilai

    return total / len(data)

# Program utama
nilai_mahasiswa = [70, 80, 90, 75, 85]

# Menampilkan nilai
tampilkan_nilai(nilai_mahasiswa)

# Tambah nilai
nilai_baru = 95
print("\nTambah nilai:", nilai_baru)
tambah_nilai(nilai_mahasiswa, nilai_baru)

# Hapus nilai
nilai_hapus = 75
print("\nHapus nilai:", nilai_hapus)
hapus_nilai(nilai_mahasiswa, nilai_hapus)

# Menghitung rata-rata
print("\nRata-rata nilai:", rata_rata(nilai_mahasiswa))

# Nilai tertinggi dan terendah
print("Nilai tertinggi:", max(nilai_mahasiswa))
print("Nilai terendah:", min(nilai_mahasiswa))